staticframework:
	cd ../../CoconutKit; ../Submodules/make-fmwk/make-fmwk.sh -o ../Binaries -u trunk Release
	cd ../../CoconutKit; ../Submodules/make-fmwk/make-fmwk.sh -o ../Binaries -u trunk Debug
	
clean:
	rm -rf ../../Binaries
