staticframework:
	cd ../../CoconutKit; ../Submodules/make-fmwk/make-fmwk.sh -o /LeStudioSDK/Binaries/CoconutKit -u trunk Release
	cd ../../CoconutKit; ../Submodules/make-fmwk/make-fmwk.sh -o /LeStudioSDK/Binaries/CoconutKit -u trunk Debug